version: '3.7'

services:
  web:
    build: .
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/blog/staticfiles
      - media_volume:/usr/src/blog/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jocsakesley
      - POSTGRES_PASSWORD=q1w2e3r4
      - POSTGRES_DB=blog_db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/blog/staticfiles
      - media_volume:/usr/src/blog/media
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume: