version: '3.7'

services:
  web:
    build: .
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/blog/staticfiles
      - media_volume:/usr/src/blog/media
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/blog/staticfiles
      - media_volume:/usr/src/blog/media
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  static_volume:
  media_volume: